Feature/add many files solution
intelematics/bricklayer pull request #29
Opened 2021-12-16 05:26 UTC by loganwang007

problem: sometimes a lot of small JSON files are distributed under several folders, this will be hard for people to grab all the contents from a single path
solution: we design a solution to fetch all the small files from a single path with immensely fast download speed by leveraging the spark distributed feature

2021-12-16 05:58 UTC, ben-thwaites requested changes

2021-12-16 05:58 UTC, ben-thwaites commented on bricklayer/catalog/file_scanner.py
> +            with ThreadPoolExecutor(max_workers=32) as executor:
I'm wondering if we can set the max_workers as paramaterizable with a default value of 32?

2021-12-16 05:58 UTC, ben-thwaites commented on bricklayer/catalog/file_scanner.py
> +                    return None
can we log/print a warning when one or more files failed to download a file?

2021-12-16 05:58 UTC, ben-thwaites commented on bricklayer/catalog/file_scanner.py
> +    Results end up in a table
Might also be worth adding a mention that this is useful when the data is highly partitioned to the point of being unable to use the standard methods for loading data from a mounted bucket.

2022-01-25 05:00 UTC, leonardMel approved these changes

2022-01-25 05:02 UTC, merged