Feature/heatmap_layer
intelematics/bricklayer pull request #30
Opened 2021-12-20 02:49 UTC by jilesD

#### Changes
* Functionality for a new heatmap layer has been added. This is implemented by the `HeatMapLayer` class, which is a subclass of `Layer`. 
* `examples/README.md` has a new section showcasing the heatmap layer.

2022-01-07 01:24 UTC, leonardMel approved these changes

2022-01-07 02:11 UTC, leonardMel requested changes
Hi Jiles, could you please bump the version and changelog as well? 
Michael lists the steps here https://github.com/intelematics/bricklayer/pull/31 
also, it's better to talk with Logan about the version/changelog change to avoid git conflicts. https://github.com/intelematics/bricklayer/pull/29

2022-01-28 01:04 UTC, ben-thwaites approved these changes

2022-02-07 04:59 UTC, leonardMel approved these changes

2022-02-14 22:56 UTC, merged